In [7]:
import numpy as np
import pandas as pd

In [8]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [9]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np
import pandas as pd

In [11]:
place =pd.read_csv("places.csv")
type=pd.read_csv("types.csv")

In [12]:
place.head

<bound method NDFrame.head of       PID                                 POIs   LATITUDE  LONGITUDE IN-TIME1  \
0    POI1                         AMBER PALACE  26.985487  75.851345    10:00   
1    POI2                   CITY PALACE JAIPUR  26.925771  75.823658     9:30   
2    POI3                 JANTAR MANTAR JAIPUR  26.924762  75.824560     9:00   
3    POI4                           HAWA MAHAL  26.923936  75.826744     9:00   
4    POI5  ALBERT HALL MUSEUM (CENTRAL MUSEUM)  26.911576  75.819487     9:00   
..    ...                                  ...        ...        ...      ...   
66  POI67   SUNRISE DREAM WORLD AMUSEMENT PARK  27.143995  75.872007    10:00   
67  POI68               BRETHREN CHURCH JAIPUR  26.901066  75.762246     9:00   
68  POI69                              MI ROAD  26.916726  75.812946     0:00   
69  POI70                        BHANGARH FORT  27.072676  76.026691     6:00   
70  POI71             SKY WALTZ BALLOON SAFARI  26.948450  75.840522     9:00  

In [13]:
type['tags']=type['PRIORITY_1']+type['PRIORITY_2']+type['PRIORITY_3']+type['PRIORITY_4']+type['PRIORITY_5']

In [14]:
type.head

<bound method NDFrame.head of       PID                                 POIs           PRIORITY_1  \
0    POI1                         AMBER PALACE  History and Culture   
1    POI2                   CITY PALACE JAIPUR  History and Culture   
2    POI3                 JANTAR MANTAR JAIPUR  History and Culture   
3    POI4                           HAWA MAHAL  History and Culture   
4    POI5  ALBERT HALL MUSEUM (CENTRAL MUSEUM)               Museum   
..    ...                                  ...                  ...   
66  POI67   SUNRISE DREAM WORLD AMUSEMENT PARK            Adventure   
67  POI68               BRETHREN CHURCH JAIPUR            Religious   
68  POI69                              MI ROAD             Shopping   
69  POI70                        BHANGARH FORT            Adventure   
70  POI71             SKY WALTZ BALLOON SAFARI            Adventure   

             PRIORITY_2         PRIORITY_3          PRIORITY_4  \
0                Museum  Local Experiences         

In [15]:
new_type=type[['PID','POIs','tags']]

# uppercase to lowercase

In [16]:
new_type['tags']=new_type['tags'].apply(lambda x:x.lower())

C:\Users\nikhi\AppData\Local\Temp\ipykernel_11036\2630989208.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_type['tags']=new_type['tags'].apply(lambda x:x.lower())


In [17]:
new_type.head

<bound method NDFrame.head of       PID                                 POIs  \
0    POI1                         AMBER PALACE   
1    POI2                   CITY PALACE JAIPUR   
2    POI3                 JANTAR MANTAR JAIPUR   
3    POI4                           HAWA MAHAL   
4    POI5  ALBERT HALL MUSEUM (CENTRAL MUSEUM)   
..    ...                                  ...   
66  POI67   SUNRISE DREAM WORLD AMUSEMENT PARK   
67  POI68               BRETHREN CHURCH JAIPUR   
68  POI69                              MI ROAD   
69  POI70                        BHANGARH FORT   
70  POI71             SKY WALTZ BALLOON SAFARI   

                                                 tags  
0   history and culturemuseumlocal experiencesscen...  
1   history and culturemuseumlocal experiencesscen...  
2                        history and culturemuseum---  
3        history and culture-local experiencesscenic-  
4                   museumhistory and culturescenic--  
..                               

In [18]:
new_type.head

<bound method NDFrame.head of       PID                                 POIs  \
0    POI1                         AMBER PALACE   
1    POI2                   CITY PALACE JAIPUR   
2    POI3                 JANTAR MANTAR JAIPUR   
3    POI4                           HAWA MAHAL   
4    POI5  ALBERT HALL MUSEUM (CENTRAL MUSEUM)   
..    ...                                  ...   
66  POI67   SUNRISE DREAM WORLD AMUSEMENT PARK   
67  POI68               BRETHREN CHURCH JAIPUR   
68  POI69                              MI ROAD   
69  POI70                        BHANGARH FORT   
70  POI71             SKY WALTZ BALLOON SAFARI   

                                                 tags  
0   history and culturemuseumlocal experiencesscen...  
1   history and culturemuseumlocal experiencesscen...  
2                        history and culturemuseum---  
3        history and culture-local experiencesscenic-  
4                   museumhistory and culturescenic--  
..                               

# TEXT VECTORIZATION

In [19]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


In [20]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=10,stop_words='english')

In [142]:
arrow=cv.fit_transform(type['tags']).toarray()

type['tags']

0     History and CultureMuseumLocal ExperiencesScen...
1     History and CultureMuseumLocal ExperiencesScen...
2          History and CultureMuseum---wildlifewildlife
3     History and Culture-Local ExperiencesScenic-wi...
4     MuseumHistory and CultureScenic--wildlifewildlife
                            ...                        
66                        Adventure----wildlifewildlife
67       Religious--Shows and Concerts-wildlifewildlife
68           ShoppingFood and Drinks---wildlifewildlife
69           AdventureScenicReligious--wildlifewildlife
70    AdventureScenic--Local Experienceswildlifewild...
Name: tags, Length: 71, dtype: object

In [116]:
arrow


array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1,

 remove redundence of tags in vector

# stamming

In [22]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [23]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [24]:
def stem(text):   
   y = []

for i in text.split:
      y.append(ps.stem(i))
        
        return " ".join(y)

IndentationError: unexpected indent (3703980420.py, line 7)

cosine dist 

In [25]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
same=cosine_similarity(arrow)

In [27]:
same[0]

array([1.        , 0.70710678, 1.        , 0.57735027, 0.        ,
       0.        , 0.        , 1.        , 0.5       , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.57735027, 0.        , 0.        ,
       0.        , 0.57735027, 0.4472136 , 0.        , 0.        ,
       0.70710678, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ])

fetch the index and then get it

In [28]:
sorted(list(enumerate(same[0])), reverse=True,key=lambda x:x[1])[1:6]

[(2, 1.0),
 (7, 1.0),
 (47, 1.0),
 (1, 0.7071067811865475),
 (25, 0.7071067811865475)]

In [29]:
def recommendation(place):
    p_index=new_type[new_type['POIs']==place].index[0]
    distances=same[p_index]
    movies_list=sorted(list(enumerate(same[0])), reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_type.iloc[i[0]].POIs)


In [30]:
recommendation('GALTAJI')

JANTAR MANTAR JAIPUR
JAL MAHAL
GATORE KI CHHATRI JAIPUR
CITY PALACE JAIPUR
RAJ MANDIR


In [31]:
new_type.iloc[7].POIs

'JAL MAHAL'

In [32]:
import re, math
from collections import Counter

In [33]:
def get_cosine(vec1, vec2):
     intersection = set(vec1.keys()) & set(vec2.keys())
     numerator = sum([vec1[x] * vec2[x] for x in intersection])
     sum1 = sum([vec1[x]**2 for x in vec1.keys()])
     sum2 = sum([vec2[x]**2 for x in vec2.keys()])
     denominator = math.sqrt(sum1) * math.sqrt(sum2)
     if not denominator:
        return 0.0
     else:
        return float(numerator) / denominator

In [34]:
WORD = re.compile(r'\w+')
def text_to_vector(text):
     words = WORD.findall(text)
     return Counter(words)

In [130]:
text="wildlife"

vec=text_to_vector(text)
vec2=text_to_vector("healthy wildlife")

In [125]:
type['tags']

0     History and CultureMuseumLocal ExperiencesScen...
1     History and CultureMuseumLocal ExperiencesScen...
2          History and CultureMuseum---wildlifewildlife
3     History and Culture-Local ExperiencesScenic-wi...
4     MuseumHistory and CultureScenic--wildlifewildlife
                            ...                        
66                        Adventure----wildlifewildlife
67       Religious--Shows and Concerts-wildlifewildlife
68           ShoppingFood and Drinks---wildlifewildlife
69           AdventureScenicReligious--wildlifewildlife
70    AdventureScenic--Local Experienceswildlifewild...
Name: tags, Length: 71, dtype: object

In [126]:
cosine_similarity(arrow)

array([[1.        , 1.        , 0.70710678, ..., 0.        , 0.        ,
        0.        ],
       [1.        , 1.        , 0.70710678, ..., 0.        , 0.        ,
        0.        ],
       [0.70710678, 0.70710678, 1.        , ..., 0.70710678, 0.70710678,
        0.        ],
       ...,
       [0.        , 0.        , 0.70710678, ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.70710678, ..., 1.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [38]:
def get_cosine(vec1, vec2):
     intersection = set(vec1.keys()) & set(vec2.keys())
     numerator = sum([vec1[x] * vec2[x] for x in intersection])
     sum1 = sum([vec1[x]**2 for x in vec1.keys()])
     sum2 = sum([vec2[x]**2 for x in vec2.keys()])
     denominator = math.sqrt(sum1) * math.sqrt(sum2)
     if not denominator:
        return 0.0
     else:
        return float(numerator) / denominator

In [152]:
vec=text_to_vector('hi')
vec2=text_to_vector(type['tags'][2])
type['tags'][6]
get_cosine(vec, vec2)


0.0

In [189]:
gh=type['tags']

In [203]:

data = [['mylife wildlife tourist']]
  
 writer = csv.DictWriter(file, fieldnames ='tags')

SyntaxError: invalid syntax (3334350436.py, line 1)

In [206]:
df2 = {'tags': 'Vikram'}

gh = gh.append(df2, ignore_index = True)

gh


C:\Users\nikhi\AppData\Local\Temp\ipykernel_11036\909545969.py:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gh = gh.append(df2, ignore_index = True)


TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

In [207]:
def Insert_row(row_number, df, row_value):
    # Starting value of upper half
    start_upper = 0
  
    # End value of upper half
    end_upper = row_number
  
    # Start value of lower half
    start_lower = row_number
  
    # End value of lower half
    end_lower = df.shape[0]
  
    # Create a list of upper_half index
    upper_half = [*range(start_upper, end_upper, 1)]
  
    # Create a list of lower_half index
    lower_half = [*range(start_lower, end_lower, 1)]
  
    # Increment the value of lower half by 1
    lower_half = [x.__add__(1) for x in lower_half]
  
    # Combine the two lists
    index_ = upper_half + lower_half
  
    # Update the index of the dataframe
    df.index = index_
  
    # Insert a row at the end
    df.loc[row_number] = row_value
   
    # Sort the index labels
    df = df.sort_index()
  
    # return the dataframe
    return df

In [208]:
Insert_row(69,gh,"himyr")

0     History and CultureMuseumLocal ExperiencesScen...
1     History and CultureMuseumLocal ExperiencesScen...
2     History and CultureMuseum---wildlifewildlifeopopo
3     History and Culture-Local ExperiencesScenic-wi...
4     MuseumHistory and CultureScenic--wildlifewildl...
                            ...                        
67    Religious--Shows and Concerts-wildlifewildlife...
68      ShoppingFood and Drinks---wildlifewildlifeopopo
69                                                himyr
70      AdventureScenicReligious--wildlifewildlifeopopo
71    AdventureScenic--Local Experienceswildlifewild...
Name: tags, Length: 72, dtype: object

NameError: name 'tokenizer' is not defined